# Generated by Django 3.2.19 on 2024-04-02 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandcenter', '0016_auto_20230922_1642'),
    ]

    operations = [
        migrations.CreateModel(
            name='JiraConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable', models.BooleanField(default=False, help_text='Enable to allow jira issues creation.')),
                ('api_key', models.CharField(default='Jira API Key', max_length=255)),
            ],
            options={
                'verbose_name': 'Jira Configuration',
            },
        ),
    ]
