# Generated by Django 3.2.19 on 2024-04-03 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandcenter', '0017_jiraconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='jiraconfiguration',
            name='api_endpoint',
            field=models.CharField(default='Jira Endpoint URL', help_text='https://company.com/rest/api/latest/', max_length=255),
        ),
        migrations.AddField(
            model_name='jiraconfiguration',
            name='default_project',
            field=models.CharField(default='Use same default project to create all tasks and sub-tasks. Only used if issue_base_mode flag set.', max_length=255),
        ),
        migrations.AddField(
            model_name='jiraconfiguration',
            name='issue_base_mode',
            field=models.BooleanField(default=False, help_text='Enable to use default project for all issues. Issues are created per ghost writer project, subtasks per finding.'),
        ),
        migrations.AlterField(
            model_name='jiraconfiguration',
            name='enable',
            field=models.BooleanField(default=False, help_text='Enable to allow jira API access.'),
        ),
    ]
