# Generated by Django 3.2.19 on 2024-04-03 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandcenter', '0018_auto_20240403_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='jiraconfiguration',
            name='jira_user',
            field=models.CharField(default='Jira Username', max_length=255),
        ),
    ]
