# Generated by Django 3.2.19 on 2024-04-03 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandcenter', '0019_jiraconfiguration_jira_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jiraconfiguration',
            name='default_project',
        ),
        migrations.RemoveField(
            model_name='jiraconfiguration',
            name='issue_base_mode',
        ),
        migrations.AddField(
            model_name='jiraconfiguration',
            name='jira_user_account_id',
            field=models.CharField(default='Jira Username Account Id', max_length=255),
        ),
        migrations.AlterField(
            model_name='jiraconfiguration',
            name='api_endpoint',
            field=models.CharField(default='Jira Endpoint URL', help_text='https://company.com', max_length=255),
        ),
    ]
