# Generated by Django 3.2.19 on 2024-04-03 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rolodex', '0047_auto_20240112_0004'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='jira_issue',
            field=models.CharField(blank=True, help_text='Provide a Jira Issue to be used for findings taking', max_length=255, null=True, verbose_name='Project Jira Issue'),
        ),
    ]
