# Generated by Django 3.2.19 on 2024-04-03 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0042_auto_20230919_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportfindinglink',
            name='sub_task_issue_id',
            field=models.TextField(blank=True, help_text='Jira SubTask IssueId', null=True, verbose_name='SubTask IssueId'),
        ),
    ]
