# Generated by Django 3.2.19 on 2024-04-03 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0043_reportfindinglink_sub_task_issue_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportfindinglink',
            old_name='sub_task_issue_id',
            new_name='jira_sub_issue',
        ),
    ]
